# Generated by Django 5.2.5 on 2025-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpendingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "주간 리포트"), ("monthly", "월간 리포트")],
                        max_length=10,
                    ),
                ),
                ("generated_date", models.DateField()),
                ("image_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-generated_date", "-created_at"],
                "unique_together": {("report_type", "generated_date")},
            },
        ),
    ]
