# Generated by Django 5.2.5 on 2025-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_sentimentanalysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spendingreport",
            name="image_path",
        ),
        migrations.AddField(
            model_name="spendingreport",
            name="json_data",
            field=models.TextField(default="{}"),
        ),
    ]
