# Generated by Django 5.2.5 on 2025-08-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=50)),
                ("nickname", models.CharField(max_length=25, unique=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("STAFF", "Staff"),
                            ("ADMIN", "Admin"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
