# Generated by Django 5.2.5 on 2025-08-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_temp_field_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="temp_field",
        ),
    ]
