# Generated by Django 5.2.5 on 2025-08-29 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
