# Generated by Django 5.2.5 on 2025-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_history", "0004_alter_transactionhistory_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "식비"),
                    ("TRANSPORTATION", "교통"),
                    ("SHOPPING", "쇼핑"),
                    ("HOUSING", "주거"),
                    ("UTILITIES", "공과금"),
                    ("ENTERTAINMENT", "문화/여가"),
                    ("HEALTH", "건강/의료"),
                    ("EDUCATION", "교육"),
                    ("FINANCE", "금융"),
                    ("OTHER", "기타"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_method",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "계좌이체"),
                    ("CARD", "카드"),
                    ("CASH", "현금"),
                    ("ETC", "기타"),
                ],
                max_length=20,
            ),
        ),
    ]
