# Generated by Django 5.2.5 on 2025-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_history", "0005_transactionhistory_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "식비"),
                    ("TRANSPORTATION", "교통"),
                    ("SHOPPING", "쇼핑"),
                    ("HOUSING", "주거"),
                    ("UTILITIES", "공과금"),
                    ("ENTERTAINMENT", "문화/여가"),
                    ("HEALTH", "건강/의료"),
                    ("EDUCATION", "교육"),
                    ("FINANCE", "금융"),
                    ("OTHER", "기타"),
                    ("INCOME", "수입"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
